### ISSUE TITLE
laozirecited.com 55 : 脧 n'est pas quán

### ISSUE THREAD

**Issue by nouveautestament** [TommPhan/TommPhan.github.io#1]
https://laozirecited.com/#55
脧 <s>quán</s>

脧 [zuī] [juān]

**Comment by TommPhan** [comment]
C'est vrai, dans l'état actuel des choses, vous verrez à la fois juān et quán dans la console :
Character: 脧
Pinyin: juān (quán)

Similaire à 仍 (prenant le sens de 扔), qui n'a pas de lecture historique de rēng, et dont je garde le caractère par souci de fidélité :
Character: 仍
Pinyin: réng (rēng)

袌 (prenant le sens de 抱), à titre de comparaison, a bien une lecture historique de bào :
Character: 袌
Pinyin: bào (bào)
